### PR TITLE
Fix wrong character length in READ inputs

### LINKED ISSUE #443: correctness fm901 -- bad output
THIS PROGRAM HAS   4 TESTS

     1    INSPECT                                2 SETS OF 2 COMPUTED LINES     
                                                 EXPECTED                       
                 COMPUTED= 
                          FILW???????35?0??
                          FILW???????35?0??

                          (?.?':
                          (?.?':
                 CORRECT:                        CORRESPONDING LINE(S) MUST MATCH
                          ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
                           =+-*/(),.$':
     2    INSPECT
                 COMPUTED= 
                          ONE THREE FIVE SEVEN NINE ELEVEN
                 CORRECT=  
                          ONE THREE FIVE SEVEN NINE ELEVEN
     3    INSPECT
                 COMPUTED= 
                          YQUARE THE WORLD IN A0 DIGHTS
                 CORRECT=  
                          AROUND THE WORLD IN 80 DAYS  
     4    INSPECT
                 COMPUTED= 
                          TO RXXXX NOT TO EXXX
                 CORRECT=  
                          TO BE OR NOT TO BE

### PR DESCRIPTION
**Pull request by jeanPerier**
Fixes #443 
The issue came from the IO code trying to get the length from the mlir value of a character address that cannot necessarily have a length.
Also fixe another other issue found while testing the code with more READ code: getDefiningOp on boxchar may fail if the boxchar is the argument.
Instead of adding yet more character special handling in the IO code to fix this, add  `cleanUpCharacterExtendedValue` to characterExprHelper that ensure that the base of an character ExtendedValue is not a boxchar. This avoid many ad-hoc handling when processing it.
Idealy I think we should enforce this at ExtendedValue creation but some places are relying on the fact that base addresses are boxchar, so in the meantime, just use the cleanUpCharacterExtendedValue when needed. I suspect Inquire and others may have similar issue, but I have not investigated yet.

### CODE REVIEW

File: flang/include/flang/Lower/CharacterExpr.h [hunk 1]
```diff
@@ -101,6 +101,10 @@ class CharacterExprHelper {
   std::pair<mlir::Value, mlir::Value>
   materializeCharacterOrSequence(mlir::Value str);
 
+  /// Temporary helper to safely get length from ExtendedValue until
+  /// migration of all character manipulation to CharBoxValue/CharArrayBoxValue.
+  mlir::Value getLen(const fir::ExtendedValue &);
```
Comment (schweitzpgi) [inline flang/include/flang/Lower/CharacterExpr.h:106]: This is redundant with `fir::getLen()` which is included in BoxValue.h, I believe.

File: flang/lib/Lower/CharacterExpr.cpp [hunk 2]
```diff
@@ -632,3 +645,30 @@ bool Fortran::lower::CharacterExprHelper::isArray(mlir::Type type) {
...
+  if (auto *unboxed = exv.getUnboxed())
+    return toDataLengthPair(*unboxed).getLen();
+  // TODO: Is length of character procedure pointer needed ?
+  llvm::report_fatal_error("BoxProc length has not length");
+}
+
+fir::ExtendedValue
+Fortran::lower::CharacterExprHelper::cleanUpCharacterExtendedValue(
+    const fir::ExtendedValue &exv) {
+  if (const auto *charBox = exv.getCharBox())
```
Comment (schweitzpgi) [inline flang/lib/Lower/CharacterExpr.cpp:667]: ExtendedValues support match syntax now. (Provides them with a more functional pattern matching syntax, to look like e.g. OCaml.)

File: flang/lib/Lower/IO.cpp [hunk 3]
```diff
@@ -324,28 +324,28 @@ static void genInputItemList(Fortran::lower::AbstractConverter &converter,
...
+    auto itemBox = charHelper.cleanUpCharacterExtendedValue(unsafeItemBox);
     auto itemAddr = fir::getBase(itemBox);
-    if (auto box = dyn_cast<fir::EmboxCharOp>(itemAddr.getDefiningOp()))
-      itemAddr = box.memref();
     auto itemTy = fir::dyn_cast_ptrEleTy(itemAddr.getType());
-    if (!itemTy)
+    if (!itemTy) {
       mlir::emitError(loc, "internal: unhandled input item type ")
           << itemAddr.getType();
+      return;
```
Comment (schweitzpgi) [inline flang/lib/Lower/IO.cpp:336]: Is this `return` really required? After the call to `emitError`, we know the IR being generated is broken already.

`emitError` is different in terms of semantics than, say, `assert`. While `assert` is going to crash and burn (for simplicity), `emitError` is meant to continue and queue up a list of errors. When lowering completes, the entire stack of errors is presented to the user, so it can catch more than just the first one.

File: flang/include/flang/Lower/CharacterExpr.h (hunk 1 above)
Comment (jeanPerier) [reply flang/include/flang/Lower/CharacterExpr.h:106]: Is there one operating on `fir::ExtendedValue` ? They are member functions under CharBoxValue and CharArrayBoxValue, but I did not saw a generic one. Anyway, this one is a bit difference since it may open box, so it needs a builder in case we have and UnboxedValue boxchar that has no parent op accessible (I think we should avoid that, but right now that happens quite often).

File: flang/lib/Lower/IO.cpp (hunk 3 above)
Comment (jeanPerier) [reply flang/lib/Lower/IO.cpp:336]: Yes, otherwise it just prints the error and immediately crashes two lines below when using itemType to find the IO function (so it does not really allow stacking errors).

File: flang/include/flang/Lower/CharacterExpr.h (hunk 1 above)
Comment (schweitzpgi) [reply flang/include/flang/Lower/CharacterExpr.h:106]: https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/include/flang/Lower/Support/BoxValue.h#L214

Comment (jeanPerier) [reply flang/include/flang/Lower/CharacterExpr.h]: Thanks, I missed it. I removed the getLen I was adding since the cleanup get rid of the UnboxedValue case.

File: flang/lib/Lower/IO.cpp [hunk 4]
```diff
@@ -1120,7 +1120,7 @@ genBuffer(Fortran::lower::AbstractConverter &converter, mlir::Location loc,
   // Helper to query [BUFFER, LEN].
   Fortran::lower::CharacterExprHelper helper(builder, loc);
   auto dataLen = helper.materializeCharacterOrSequence(
-      fir::getBase(converter.genExprValue(*e)));
+      fir::getBase(converter.genExprAddr(*e)));
```
Comment (jeanPerier) [inline flang/lib/Lower/IO.cpp:1123]: I added a fix  here for a new fm909 lowering issue that appeared when using the runtime with the character array output fix.

**Review by schweitzpgi — APPROVED** [review]
