### PR TITLE
Use fir.array<?xfir.char<kind>> for the type of the fir.boxchar address

### LINKED ISSUE #536: 'fir.embox' op LEN parameters require !fir.type type
```
% cat cp.f
      ! spec2k sixtrack
      subroutine cpltwis(typ)
      character*16 typ
      write(11) typ
      end
```
```
% bbc cp.f
error: loc("cp.f":4:17): 'fir.embox' op LEN parameters require !fir.type type
```

### PR DESCRIPTION
**Pull request by jeanPerier**
This was a left over TODO from character refactoring, scalar character base address type `fir.ref<fir.char>` should not be propagated anymore since character related utilities are expecting a sequence type with the length
as first dimension.
This prevented unformatted IO with scalar characters to lower.

Fixes #536.

### CODE REVIEW

File: flang/lib/Lower/CharacterExpr.cpp [hunk 1]
```diff
@@ -187,8 +187,10 @@ Fortran::lower::CharacterExprHelper::toExtendedValue(mlir::Value character,
       return materializeValue(fir::getBase(character));
     }
   }
-  if (!resultLen)
+  if (!resultLen) {
     mlir::emitError(loc, "no dynamic length found for character");
+    llvm::report_fatal_error("fatal");
```
Comment (schweitzpgi) [inline flang/lib/Lower/CharacterExpr.cpp:192]: Why two errors? This code uses emitError in a lot of places. Maybe a `return` is required here?

File: flang/lib/Lower/Bridge.cpp [hunk 2]
```diff
@@ -2117,16 +2101,25 @@ class FirConverter : public Fortran::lower::AbstractConverter {
           auto charLen = x.charLen();
           if (replace) {
             auto symBox = lookupSymbol(sym);
-            auto unboxchar = charHelp.createUnboxChar(symBox.getAddr());
-            auto boxAddr = unboxchar.first;
+            mlir::Value boxAddr = symBox.getAddr();
```
Comment (schweitzpgi) [inline flang/lib/Lower/Bridge.cpp:2104]: `auto`?

File: flang/lib/Lower/IntrinsicCall.cpp [hunk 3]
```diff
@@ -1194,32 +1194,34 @@ mlir::Value IntrinsicLibrary::genIAnd(mlir::Type resultType,
...
-mlir::Value IntrinsicLibrary::genIchar(mlir::Type resultType,
-                                       llvm::ArrayRef<mlir::Value> args) {
+fir::ExtendedValue
+IntrinsicLibrary::genIchar(mlir::Type resultType,
+                           llvm::ArrayRef<fir::ExtendedValue> args) {
   // There can be an optional kind in second argument.
   assert(args.size() == 2);
+  auto charBox = args[0].getCharBox();
+  if (!charBox)
+    llvm::report_fatal_error("expected character scalar");
```
Comment (schweitzpgi) [inline flang/lib/Lower/IntrinsicCall.cpp:1204]: The mlir emitError reports a nicer error message to the user. But report_fatal_error halts the compiler dead in its tracks. It seems like this type check should've already happened, so maybe a "crash immediately" is good enough here.

**Review by schweitzpgi — APPROVED** [review]
Thanks for getting rid of some more distributed special CHARACTER handling here.

File: flang/lib/Lower/IntrinsicCall.cpp (hunk 3 above)
Comment (jeanPerier) [reply flang/lib/Lower/IntrinsicCall.cpp:1204]: I like that `mlir::emitError()` gives the user line programs, and not stopping is fine when we still manage to spit out an mlir module, but quite often we just go the undefined behavior after we emitted an error since we do not expect empty `mlir::Value` coming out from these functions. In debug mode, we usually hit an mlir/llvm assert quick soon after, but in release that can ends-up far and weird.

So my guideline is to use `mlir::emitError` when I know compilation will succeed but the compiled program will be wrong (let's say we are skipping a temp copy and we know we are wrong), and to use `llvm::report_fatal_error` if I cannot return a non empty `mlir::Value` from a function that should.

Is their a way to use mlir loc in `llvm::report_fatal_error` ?

File: flang/lib/Lower/CharacterExpr.cpp (hunk 1 above)
Comment (jeanPerier) [reply flang/lib/Lower/CharacterExpr.cpp:192]: cheap debug leftover, I wanted a stack dump here instead of later when the empty mlir::Value is used. If there is a way to dump the user `loc` in `llvm::report_fatal_error` I would favor it to avoid returning an empty value.
