### PR TITLE
[OpenMP] Fixes for unstructured code in OpenMP regions

### LINKED ISSUE #1192: Outermost OpenMP do-loop and cycle fails to compile
As per comment in https://github.com/flang-compiler/f18-llvm-project/pull/1178:

```
program lineloop
  implicit none
  INTEGER ::  n
  
  !$OMP PARALLEL DO NUM_THREADS(2) SCHEDULE(STATIC,1) PRIVATE(n)
  DO n = 1, 2
     IF ( n > 2 )  CYCLE
  END DO
  !$OMP END PARALLEL DO
end program lineloop
```
fails with an assertion:
```
bbc: /data/f18-llvm-project/flang/lib/Lower/OpenMP.cpp:117: void createEmptyRegionBlocks(fir::FirOpBuilder &, std::list<Fortran::lower::pft::Evaluation> &): Assertion `eval.block->empty() && "block is not empty"' failed.
```

### PR DESCRIPTION
**Pull request by kiranchandramohan**
The following changes are made for OpenMP operations with unstructured regions to ensure that empty region blocks are created only once. This helps fix issues seen in the SNAP application.

1. For combined constructs the outer operation is considered a structured region and the inner one as the unstructured.
2. Added a condition to ensure that we create new blocks only once for nested unstructured OpenMP constructs.
    
Tests are added for checking the structure of the CFG.

Fixes #1192

### CODE REVIEW

File: flang/include/flang/Lower/PFTBuilder.h [hunk 1]
```diff
@@ -138,6 +138,11 @@ using Directives =
                parser::OpenACCDeclarativeConstruct, parser::OpenMPConstruct,
                parser::OpenMPDeclarativeConstruct, parser::OmpEndLoopDirective>;
 
+using Continues =
+    std::tuple<parser::ContinueStmt> ;
+template <typename A>
+static constexpr bool isContinueStmt{common::HasMember<A, Continues>};
+
```
Comment (vdonaldson) [inline flang/include/flang/Lower/PFTBuilder.h:145]: Kiran - `PFTBuilder.h` has a template for recognizing individual statements.  Given an `eval e`, it should be possible to query if `e.isA<parser::ContinueStmt>`.

However, if the idea is to find the block containing an "exit" `ContinueStmt`, it should be possible to get that automatically, in which case special case code should not be needed.  Like other constructs, a `DoConstruct` has a `constructExit` eval that should be set to that eval.  Depending on the `eval` passed to `createBodyOfOp` that `constructExit` eval may already be directly available.  Given that exit eval (and assuming it is the first eval in its block, which it should be), then its `block` member is the block of interest.

File: flang/lib/Lower/PFTBuilder.cpp [hunk 2]
```diff
@@ -317,10 +317,12 @@ class PFTBuilder {
...
       Fortran::lower::pft::EvaluationList &evaluationList =
           *eval->evaluationList;
-      if (!evaluationList.empty() && evaluationList.back().isConstruct()) {
+      if (!evaluationList.empty() && (evaluationList.back().isConstruct() ||
+                                      evaluationList.back().isDirective())) {
         static const parser::ContinueStmt exitTarget{};
         addEvaluation(
-            lower::pft::Evaluation{exitTarget, pftParentStack.back(), {}, {}});
+            lower::pft::Evaluation{exitTarget, pftParentStack.back(), {}, {}})
+            .isNewBlock = true;
```
Comment (vdonaldson) [inline flang/lib/Lower/PFTBuilder.cpp:325]: Branch analysis should automatically set the `isNewBlock` flag, at least for looping constructs.  Are there "straight-line" OpenMP constructs that aren't automatically setting this flag?  (If yes, there is another option for getting an "exit" for it.)  For looping constructs, if the `ContinueStmt` is not being marked as a new block, it is probably in the wrong place, perhaps with respect to an `OmpEndLoopDirective` eval.

**Review by vdonaldson — COMMENTED** [review]
Some general comments -

It might be a good idea to split off the cherry pick changes that avoid the buggy error message.  That fix is a prerequisite to, and independent of other fixes.

You can get additional testing of unstructured code by forcing unstructured code generation for all loops with the `-no-structured-fir` developer flag.  The intent is to make it easier to exercise less common unstructured code cases without actually having to put in unstructured branches.

File: flang/lib/Lower/PFTBuilder.cpp (hunk 2 above)
Comment (kiranchandramohan) [reply flang/lib/Lower/PFTBuilder.cpp:325]: For looping constructs, the `ContinueStmt` is marked as a new block. It is for the outer parallel construct that the `ContinueStmt` is not marked as a new block. Due to this, previously, they end up sharing the same block when `createEmptyRegionBlocks` is called for both.

**Comment by kiranchandramohan** [comment]
> It might be a good idea to split off the cherry pick changes that avoid the buggy error message. That fix is a prerequisite to, and independent of other fixes.

Done. Created a separate PR https://github.com/flang-compiler/f18-llvm-project/pull/1399.

> You can get additional testing of unstructured code by forcing unstructured code generation for all loops with the -no-structured-fir developer flag. The intent is to make it easier to exercise less common unstructured code cases without actually having to put in unstructured branches.

OK. will try this.

File: flang/lib/Lower/PFTBuilder.cpp (hunk 2 above)
Comment (vdonaldson) [reply flang/lib/Lower/PFTBuilder.cpp:325]: If I understand how code should look for parallel regions, not all inserted `ContinueStmt`s are branch targets.  Unstructured constructs need not have branches that exit the construct.  A loop could be unstructured due to the presence of a simple `goto` entirely local to the loop body, or some nested construct with an `ExitStmt`.  I believe all basic block recognition is currently local to PFT routine `analyzeBranches`.

That said, if these `ContinueStmt`s must always be in their own (unstructured) basic block, or you can at least determine that forcing such a block all the time is not a correctness problem, then it might be ok to initially force creation of such blocks all the time, with the option of going back later to sharpen up the code to only set it when needed.  The `-no-structured-fir` flag should make that testing a little more robust.

It should be easier to investigate the problem once PR #1399 is available; thanks for splitting that out.

File: flang/include/flang/Lower/PFTBuilder.h (hunk 1 above)
Comment (kiranchandramohan) [reply flang/include/flang/Lower/PFTBuilder.h]: Thanks, I completely missed that, I have switched to using isA<parser::ContinueStmt>.

Yes, good point about the constructExit. Question is what about for other non-looping constructs?

Also, going back to a point you raised in https://github.com/flang-compiler/f18-llvm-project/issues/1192, quoting you below.
"although there is some question as to whether the ContinueStmt should be inserted before or after the `OmpEndLoopDirective` Evaluation. (It may be that either way is ok.)"

I think the reason the branch might be missing is that the ContinueStmt is added after the `OmpEndLoopDirective` Evaluation. It might all work if it is before. I will give that a try.

Comment (vdonaldson) [reply flang/include/flang/Lower/PFTBuilder.h]: Yes, swapping the order of the `ContinueStmt` and the `OmpEndLoopDirective` is definitely worth a look.

File: flang/lib/Lower/PFTBuilder.cpp (hunk 2 above)
Comment (kiranchandramohan) [reply flang/lib/Lower/PFTBuilder.cpp]: I have now removed the requirement for `ContinueStmt`s to be always in their own basic block. This became possible after restricting `createEmptyRegionBlocks` to not recurse into nested OpenMPConstructs/Directives.

File: flang/include/flang/Lower/PFTBuilder.h (hunk 1 above)
Comment (kiranchandramohan) [reply flang/include/flang/Lower/PFTBuilder.h]: I am now using the `constructExit` to find the terminator block.

I tried to create the `ContinueStmt` before the `OmpEndLoopDirective` but that did not work. Not sure whether my approach for doing this was correct.

**Comment by kiranchandramohan** [comment]
@vdonaldson @Leporacanthicus After investigating a bit further I found out that we only have to avoid creating empty blocks multiple times to fix the issues. This is achieved by checks for combined constructs (!$omp parallel do) and nested constructs (parallel, do). This simplifies the code a lot.

**Review by vdonaldson — APPROVED** [review]
This set of changes looks good to me.  It lets the normal control flow machinery do its usual work, and keeps directive-centric changes in directive-centric code.

Thanks for digging into this.

**Review by schweitzpgi — APPROVED** [review]
