### PR TITLE
Ensure used module variables are mapped when lowering internal procedures.

### LINKED ISSUE #941: symbol is not mapped to any IR value
The following piece of code crashes `bbc`

```fortran
      module compart
      integer, allocatable :: nsegs(:)
      end module


      subroutine ingrowth(ip)

      use compart

      implicit none

      integer ip
      
      return
      contains

      subroutine decay
      implicit none
      integer j
      j = nsegs(ip)
      return
      end subroutine decay

      end subroutine ingrowth
```

and stack dump

```
bbc ingrowth.f 
error: loc("./ingrowth.f":20:7): symbol is not mapped to any IR value
LLVM ERROR: aborting
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.  Program arguments: /home/ryuta/packages/llvm/flang/build/bin/bbc ingrowth.f
 #0 0x00007fd2123696d3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x2256d3)
 #1 0x00007fd21236706e llvm::sys::RunSignalHandlers() (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x22306e)
 #2 0x00007fd212369d5f SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fd21643e630 __restore_rt sigaction.c:0:0
 #4 0x00007fd211978387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007fd211979a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007fd212289bc3 llvm::report_fatal_error(llvm::Twine const&, bool) (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x145bc3)
 #7 0x00007fd212289a26 (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x145a26)
 #8 0x00007fd2160ea5c2 (/home/ryuta/packages/llvm/flang/build/lib/libFortranLower.so.13git+0x1fc5c2)
 #9 0x00007fd216177dc2 (/home/ryuta/packages/llvm/flang/build/lib/libFortranLower.so.13git+0x289dc2)
```

### PR DESCRIPTION
**Pull request by jeanPerier**
Fixes #941 and similar issues.

When an internal procedure is defined inside a module procedure, it may access the module variables. These accesses are not materialized by associated symbols in the internal procedure scope, so lowering must instantiate all the parent module variables before lowering the internal procedure so that any reference to the module symbols can be resolved as it is done with module procedures currently. Unused instantiation are later discarded by dead code elimination.
This is done by improving the PFT infrastructure to easily look for ModuleLikeUnit ancestors of a FunctionLikeUnit.

Also update the case where the internal procedure is not in a module procedure but simply in a procedure that uses module variables. This case compiled and worked, but the module variable was passed via the host tuple when it can simply be instantiated directly from the module address inside the internal procedure.

Finally, a front-end fix was required in the case where module variables used in the host procedure are referenced inside the internal procedure in mis-parsed array-ref. A previous similar front-end fix did not account for the module variable case. This fixed was already review and merged in LLVM and is simply cherry-picked here.

### CODE REVIEW

**Review by psteinfeld — APPROVED** [review]
All builds, tests, and looks good to me.

But I don't understand this code, so you might want to wait for a review from someone more knowledgeable before merging.

File: flang/include/flang/Lower/PFTBuilder.h [hunk 1]
```diff
@@ -90,6 +90,25 @@ using MutableReferenceVariant = ReferenceVariantBase<false, A...>;
 using PftNode = MutableReferenceVariant<Program, ModuleLikeUnit,
                                         FunctionLikeUnit, Evaluation>;
 
+/// Class to be inherited by all PFT nodes that have parents.
+/// It provides the ability to traverse the PFT tree upwards.
+struct ChildNode {
```
Comment (schweitzpgi) [inline flang/include/flang/Lower/PFTBuilder.h:95]: This name seems backwards as "ChildNode" is being used to build a parent relation.

Is it really needed? Playing Devil's advocate: in the parse tree, inheritance like this is rejected in favor of denotational convergence. For example, every node in the PFT could have a member named `parent` when applicable (which I think is already the case), and a template function can be written to access `that.parent` when `that` is any type `a` with such a member. (i.e., like `.u`, `.t`, and `.v` members in the raft of parse tree classes.)

```c++
template <typename ParentType, typename A>
  ParentType *getAncestor(const A &that) {
    if (auto *seekedParent = that.parent.getIf<ParentType>())
      return seekedParent;
    return parent.visit(
        common::visitors{[](Program &p) -> ParentType * { return nullptr; },
                         [](auto &p) -> ParentType * {
                           return template getAncestor<ParentType>(p);
                         }});
  }
```

File: flang/lib/Lower/Bridge.cpp [hunk 2]
```diff
@@ -205,6 +205,19 @@ class FirConverter : public Fortran::lower::AbstractConverter {
       declareFunction(f);
   }
 
+  /// Return the host symbol if this is the symbol of an internal procedure
```
Comment (schweitzpgi) [inline flang/lib/Lower/Bridge.cpp:208]: "this" feels a little dangling here. Does it mean the argument, `sym`?

File: flang/lib/Lower/Bridge.cpp [hunk 3]
```diff
@@ -205,6 +205,19 @@ class FirConverter : public Fortran::lower::AbstractConverter {
...
+  /// variable that belongs to the host procedure.
+  const Fortran::semantics::Symbol *
+  getIfHostEscapingSymbol(const Fortran::semantics::Symbol &sym) {
```
Comment (schweitzpgi) [inline flang/lib/Lower/Bridge.cpp:211]: Do we need to be precise that this is a _host procedure_ here? (Distinguish it from a host module?)

File: flang/lib/Lower/Bridge.cpp [hunk 4]
```diff
@@ -2265,9 +2277,9 @@ class FirConverter : public Fortran::lower::AbstractConverter {
     // The front-end is currently not adding module variables referenced
```
Comment (schweitzpgi) [inline flang/lib/Lower/Bridge.cpp:2277]: Do we just want to implement what this comment is suggesting at this point? Would it make all this easier if they were just resolved in the front end?

File: flang/lib/Lower/Bridge.cpp (hunk 3 above)
Comment (jeanPerier) [reply flang/lib/Lower/Bridge.cpp]: Right, I went for `getIfHostProcedureSymbol` and actually modified the code because as you pointed out, "belongs to module" does not imply "use associated", so my logic was broken if the front-end ever starts using HostAssociated symbols for module variables inside contained procedures.

File: flang/include/flang/Lower/PFTBuilder.h (hunk 1 above)
Comment (jeanPerier) [reply flang/include/flang/Lower/PFTBuilder.h]: > Is it really needed?

No, I thought it was nicer to use a bit of class hierarchy to confer the property of being a child node. But your suggestion is less intrusive,. I went for it, thanks.

File: flang/lib/Lower/Bridge.cpp (hunk 4 above)
Comment (jeanPerier) [reply flang/lib/Lower/Bridge.cpp:2280]: We should discuss that with Peter. It may be easier for lowering, though my experience with trying to enforce the equivalent for host associated symbols in internal procedures is that it is hard to enforce this is done properly in name resolution (i.e. they are several places where this creation must happen, and from a front-end perspective, it is not needed so not properly enforced).
The most robust alternative I can think of would be to collect all the symbols referred inside a procedure body when building the PFT instead of using the scopes. But this would add an extra deep pass over the parse-tree.

Comment (schweitzpgi) [reply flang/lib/Lower/Bridge.cpp:2280]: Indeed. Let's perform some due diligence here to cover the bases.

**Review by schweitzpgi — APPROVED** [review]
