### PR TITLE
Place induction variables in column major order

### LINKED ISSUE #729: Incorrect values with array i/o
Derived from f95 test suite
```
integer, dimension (1,1,2,3) :: a
integer, parameter :: n=1
a(1,1,2,:) = (/1,2,3/)
print *, a(1,1,2,1), a(1,1,2,2), a(1,1,2,3)
write(6,*) A (:, 1:N, 2, 1:3)
write(6,*) A (:, 1:N, 2, 3:1:-1)
end
```
```
% flang f.f90
% a.out
 1 2 3
 1 0 2
 3 0 0
```
```
% gfortran f.f90
% a.out
           1           2           3
           1           2           3
           3           2           1
```
The spacing between the numbers is implementation defined.

### PR DESCRIPTION
**Pull request by jeanPerier**
Fixes #729.
The issue came from bad order of induction variables in array expressions loops. This was a generic problem, probably not caught because most of the multiple dimension regressions tests have the same extents.
The order of the loops was OK, but the comment about it not OK.

Note that the issue was exposed in #729 because lowering is making a copy of the array slice for the IO runtime call. It should not. It should instead create a descriptor for the array slice. For output IO, that is just a perf issue, for input IO, that is wrong. I am working on a fix for that in a different PR since that is a different issue.

### CODE REVIEW

File: flang/test/Lower/array-expression.f90 [hunk 1]
```diff
@@ -426,4 +426,18 @@ subroutine test18
...
+! CHECK-LABEL: func @_QPtest_column_and_row_order(
+subroutine test_column_and_row_order(x)
+  real :: x(2,3)
+  ! CHECK-DAG: %[[c2:.*]] = fir.convert %c2{{.*}} : (i64) -> index
+  ! CHECK-DAG: %[[column_extent:.*]] = subi %[[c2]], %c1{{.*}} : index
+  ! CHECK-DAG: %[[c3:.*]] = fir.convert %c3{{.*}} : (i64) -> index
+  ! CHECK-DAG: %[[row_extent:.*]] = subi %[[c3]], %c1{{.*}} : index
+  ! CHECK: fir.do_loop %[[row:.*]] = %c0{{.*}} to %[[row_extent]]
+    ! CHECK: fir.do_loop %[[column:.*]] = %c0{{.*}} to %[[column_extent]]
+      ! CHECK: = fir.array_update %{{.*}}, %{{.*}}, %[[column]], %[[row]] : (!fir.array<2x3xf32>, f32, index, index) -> !fir.array<2x3xf32>
```
Comment (mleair) [inline flang/test/Lower/array-expression.f90:438]: nit: spacing

File: flang/test/Lower/array-expression.f90 [hunk 2]
```diff
@@ -426,4 +426,18 @@ subroutine test18
   row_i => array(i, :)
 end subroutine test18
 
+! CHECK-LABEL: func @_QPtest_column_and_row_order(
+subroutine test_column_and_row_order(x)
```
Comment (mleair) [inline flang/test/Lower/array-expression.f90:430]: You do not need a CHECK-SAME on x (e.g., %arg0) ?

Comment (jeanPerier) [reply flang/test/Lower/array-expression.f90:430]: No because there is no need to capture the argument in this test. The test is really only focused on the induction variables/loop order, not really what the loops are doing and on what.
There is always a trade of in lit tests between capturing enough patterns to demonstrate a property of the lowered IR and avoiding capturing too much to avoid corelating the test with other IR properties that are not central to the test and would break the test if changed. Here, argument lowering is not something needed for the test, so I rather not add any related checks.

File: flang/test/Lower/array-expression.f90 (hunk 1 above)
Comment (jeanPerier) [reply flang/test/Lower/array-expression.f90]: It was on purpose because fir.loop are printed with indentation so I thought it would be nice the reflect this structure. But other lit tests are not doing that, so you are right that it looks weird. I have flattened it.

File: flang/lib/Lower/ConvertExpr.cpp [hunk 3]
```diff
@@ -2116,7 +2116,9 @@ class ArrayExprLowering {
           loc, zero, i.value(), one, /*unordered=*/false,
           /*finalCount=*/false, mlir::ValueRange{innerArg});
       innerArg = loop.getRegionIterArgs().front();
-      ivars.push_back(loop.getInductionVar());
+      // Store induction vars in column major order, which is what FIR array ops
+      // expect.
+      ivars[loopDepth - 1 - i.index()] = loop.getInductionVar();
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertExpr.cpp:2121]: Thanks for the fix.

I think in other spots that I built the list backwards and then just reversed it. Forgot the reverse call here.

File: flang/lib/Lower/ConvertExpr.cpp [hunk 4]
```diff
@@ -2099,13 +2099,13 @@ class ArrayExprLowering {
...
     fir::DoLoopOp inner;
     auto innerArg = destination.getResult();
     mlir::Value outerRes;
-    llvm::SmallVector<mlir::Value> ivars;
-    auto insPt = builder.saveInsertionPoint();
     const auto loopDepth = loopUppers.size();
+    llvm::SmallVector<mlir::Value> ivars(loopDepth);
+    auto insPt = builder.saveInsertionPoint();
     assert(loopDepth > 0);
     for (auto i : llvm::enumerate(llvm::reverse(loopUppers))) {
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertExpr.cpp:2110]: Can't you just remove this call to llvm::reverse here? Other than the comment and the regression test, that ought to be about it.

File: flang/lib/Lower/ConvertExpr.cpp [hunk 5]
```diff
@@ -2099,13 +2099,13 @@ class ArrayExprLowering {
       }
     }
 
-    // Iteration space is created with outermost columns, innermost rows
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertExpr.cpp:2102]: The comment looks correct to me, btw. Since FIR is column-major, the inner most loop should visit the row (left most index first), and so on until the outermost loop, which should visit the column (right most index).  That takes better advantage of cache locality.

File: flang/test/Lower/array-expression.f90 [hunk 6]
```diff
@@ -426,4 +426,18 @@ subroutine test18
...
+  real :: x(2,3)
```
Comment (schweitzpgi) [inline flang/test/Lower/array-expression.f90:431]: 2 is the row. 3 is the column. These appear to be flipped?

File: flang/lib/Lower/ConvertExpr.cpp (hunk 4 above)
Comment (schweitzpgi) [reply flang/lib/Lower/ConvertExpr.cpp:2110]: Nah. My bad. This reverse is needed to create the loops "inside out". The vector of indices can be reversed afterwards.

File: flang/lib/Lower/ConvertExpr.cpp (hunk 5 above)
Comment (jeanPerier) [reply flang/lib/Lower/ConvertExpr.cpp:2102]: My bad, I understood column/rows as "going through data of a column in the outermost  loop" instead of "going through the column indexes in the outermost loop". I reverted this comment and fixed the new test ssa value naming.

**Review by schweitzpgi — APPROVED** [review]
thanks for the fixes.
