### PR TITLE
Delete code that was redundantly removing the elided extents before t…

### LINKED ISSUE #942: automatic arrays
I managed to crash `bbc` with the following code:

```fortran
MODULE global_module

    IMPLICIT NONE
    PUBLIC
    SAVE

    INTEGER, PARAMETER :: i_knd = SELECTED_INT_KIND( 8 )
    INTEGER, PARAMETER :: r_knd = SELECTED_REAL_KIND( 13 )

END MODULE global_module


MODULE sn_module

    USE global_module

    IMPLICIT NONE
    PUBLIC
    SAVE

    INTEGER(i_knd) :: nang = 1

END MODULE sn_module



MODULE dim1_sweep_module

    USE global_module
    USE sn_module

    IMPLICIT NONE

    PUBLIC :: dim1_sweep

    CONTAINS

    SUBROUTINE dim1_sweep( id )

        INTEGER(i_knd), INTENT(IN) :: id
        REAL(r_knd), DIMENSION(nang,2) :: hv

    END SUBROUTINE dim1_sweep

END MODULE dim1_sweep_module
```

and here's the stack dump:

```
bbc shape_size.f90 
bbc: /home/ryuta/packages/llvm/flang/f18-llvm-project/flang/lib/Lower/FIRBuilder.cpp:118: llvm::SmallVector<mlir::Value> elideExtentsAlreadyInType(mlir::Type, mlir::ValueRange): Assertion `shape.size() == arrTy.getDimension()' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.  Program arguments: /home/ryuta/packages/llvm/flang/build/bin/bbc shape_size.f90
 #0 0x00007fb4fc3886d3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x2256d3)
 #1 0x00007fb4fc38606e llvm::sys::RunSignalHandlers() (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x22306e)
 #2 0x00007fb4fc388d5f SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fb50045d630 __restore_rt sigaction.c:0:0
 #4 0x00007fb4fb997387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007fb4fb998a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007fb4fb9901a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007fb4fb990252 (/lib64/libc.so.6+0x2f252)
 #8 0x00007fb500363c6f (/home/ryuta/packages/llvm/flang/build/lib/libFortranLower.so.13git+0x456c6f)
 #9 0x00007fb500362fd6 Fortran::lower::FirOpBuilder::allocateLocal(mlir::Location, mlir::Type, llvm::StringRef, llvm::StringRef, llvm::ArrayRef<mlir::Value>, llvm::ArrayRef<mlir::Value>, bool) (/home/ryuta/packages/llvm/flang/build/lib/libFortranLower.so.13git+0x455fd6)
#10 0x00007fb5003419ec createNewLocal(Fortran::lower::AbstractConverter&, mlir::Location, Fortran::lower::pft::Variable const&, mlir::Value, llvm::ArrayRef<mlir::Value>, llvm::ArrayRef<mlir::Value>) ConvertVariable.cpp:0:0
```

### PR DESCRIPTION
**Pull request by schweitzpgi**
…he builder elided those extents.

Fixes #942.

### CODE REVIEW

File: flang/lib/Lower/ConvertVariable.cpp [hunk 1]
```diff
@@ -392,17 +392,7 @@ static mlir::Value createNewLocal(Fortran::lower::AbstractConverter &converter,
...
-      // elide the constant dimensions before construction
-      assert(shape.size() == arrTy.getDimension());
-      llvm::SmallVector<mlir::Value> args;
-      auto typeShape = arrTy.getShape();
-      for (unsigned i = 0, end = arrTy.getDimension(); i < end; ++i)
-        if (typeShape[i] == fir::SequenceType::getUnknownExtent())
-          args.push_back(shape[i]);
-      return builder.allocateLocal(loc, ty, nm, symNm, args, lenParams, isTarg);
-    }
+  // Let the builder do all the heavy lifting.
```
Comment (vdonaldson) [inline flang/lib/Lower/ConvertVariable.cpp:395]: Comment might be unnecessary / confusing?

**Review by vdonaldson — APPROVED** [review]

File: flang/lib/Lower/ConvertVariable.cpp (hunk 1 above)
Comment (schweitzpgi) [reply flang/lib/Lower/ConvertVariable.cpp:395]: True. On the other hand, I sort of wanted to indicate "don't overthink this here, this function is just a thin veneer over the real thing."
