### PR TITLE
Fix for #273

### LINKED ISSUE #273: Replace WhereOp with IfOp in the code
The parser and pretty printer were updated a while back to accept `fir.if { ... } else { ... }` but the name of the class was left as a TODO. The class `fir::WhereOp` should be renamed `fir::IfOp` to help reduce confusion. One caveat is that a bare `IfOp` may not be sufficient as other MLIR dialect's have their own `IfOp`. Replacement should spell out `fir::IfOp` to be clear.

### PR DESCRIPTION
**Pull request by SouraVX**
This fixes #273 . Please share feedback. I think for this too, we have to upstream parts of this(that can be upstreamed).

### CODE REVIEW

File: flang/lib/Optimizer/Transforms/RewriteLoop.cpp [hunk 1]
```diff
@@ -147,31 +146,30 @@ class CfgIfConv : public mlir::OpRewritePattern<fir::WhereOp> {
     auto opPosition = rewriter.getInsertionPoint();
     auto *remainingOpsBlock = rewriter.splitBlock(condBlock, opPosition);
     mlir::Block *continueBlock;
-    if (where.getNumResults() == 0) {
+    if (ifop.getNumResults() == 0) {
```
Comment (schweitzpgi) [inline flang/lib/Optimizer/Transforms/RewriteLoop.cpp:149]: This probably should be `ifOp`.

Comment (SouraVX) [reply flang/lib/Optimizer/Transforms/RewriteLoop.cpp]: Thanks for pointing this out, must've missed out.
Done changes!

**Comment by SouraVX** [comment]
Once reviewing completes here, as discussed, should we also move whole/parts of it to Phab ?
