### PR TITLE
Use array_coor on where masks instead of fir.coordinate_of

### LINKED ISSUE #855: error: 'fir.coordinate_of' op cannot find coordinate with unknown extents
`bbc` spits the error message

```
error: 'fir.coordinate_of' op cannot find coordinate with unknown extents
oops, pass manager reported failure
```

I think this is related to the F90 transformational array intrinsic function
(7.2.2 of https://www.mcs.anl.gov/~itf/dbpp/text/node84.html)

Here's the code to reproduce:

```fortran
MODULE inner_module

  USE geom_module, ONLY: nx, ny, nz

  IMPLICIT NONE

  PRIVATE

  CONTAINS


  SUBROUTINE inner_df_calc ( flux0pi )

    INTEGER, PARAMETER :: i_knd = SELECTED_INT_KIND( 8 )
    INTEGER, PARAMETER :: r_knd = SELECTED_REAL_KIND( 13 )
    REAL(r_knd), PARAMETER :: one  = 1.0_r_knd
    REAL(r_knd), PARAMETER :: tolr=1.0E-12_r_knd
    REAL(r_knd), DIMENSION(nx,ny,nz), INTENT(INOUT) :: flux0pi

    WHERE( ABS( flux0pi ) < tolr )
      flux0pi = one
    END WHERE

  END SUBROUTINE inner_df_calc

END MODULE inner_module
```

`geom_module.mod` contains

```
!mod$ v1 sum:3661f8d61ddb86a9
module geom_module
integer(4),parameter::i_knd=4_4
intrinsic::selected_int_kind
integer(4)::nx
integer(4)::ny
integer(4)::nz
end
```

### PR DESCRIPTION
**Pull request by jeanPerier**
[Edit: changed from fir.array_load based solution to fir.array_coor after discussion].

Fixes #855.
fir.coordinate_of was used to fetch pre-computed values inside
where statements in a way that was only valid with compile time
constant shape masks.

To fix this, there was three alternatives I considered:
 - Keep fir.coordinate_of, but collapse dimensions an compute offset
   in lowering.
 - Use fir.array_coor, taking into account lower bounds.
 - Use fir.array_load + fir.array_fetch, directly using loop indexes.

~~I went for the last one that was the easiest to deploy, and adds the less index computation noise inside the fir loops, which as far as I understand it should be better for future loop optimizations (affine...).~~

I went for the fir.array_coor because using fir.array_load was creating array_loads of the masks that were used in different loop nests, which is not the nominal usage of fir.array_load. Besides, fir.array_load is meant to deal with array aliasing, and there is none here since masks are lowered into temps.

Fir.array_coor generate less index computation noise inside the fir loops
compared to collapsing fir.coordinate_of. As far as I understand it,
this should be better for future loop optimizations (affine...).

### CODE REVIEW

**Review by vdonaldson — APPROVED** [review]

File: flang/test/Lower/where.f90 [hunk 1]
```diff
@@ -107,3 +110,28 @@
...
+  integer(8) :: n
+  real :: x(n, n)
+  ! CHECK-DAG: fir.array_load %[[x]](%{{.*}}) : (!fir.ref<!fir.array<?x?xf32>>, !fir.shape<2>) -> !fir.array<?x?xf32>
+  ! CHECK-DAG: %[[two:.*]] = constant 2.0{{.*}} : f32
+  ! CHECK: %[[tvec:.*]] = fir.allocmem !fir.array<?x?x!fir.logical
+  ! CHECK-DAG: fir.array_load %[[tvec]]
+  ! CHECK: fir.do_loop
+  ! CHECK: cmpf ogt, %{{.*}}, %[[two]]
+  ! CHECK: fir.array_merge_store %{{.*}}, %{{.*}} to %[[tvec]]
+  ! CHECK: %[[tmask:.*]] = fir.array_load %[[tvec]]
```
Comment (schweitzpgi) [inline flang/test/Lower/where.f90:126]: This looks quite off to me. Why is the array being merged and reloaded in the body of the expression?

Comment (jeanPerier) [reply flang/test/Lower/where.f90:126]: It's not the body of a single expression, it is the body of the where statement where several things must happen in order.
- the mask is first evaluated in a temp (first fir.array_load, fir.do_loop and fir.array_merge_store)
- and then the result array value is used in the actual assignment inside the where statement (hence the second fir.array_load of the temp).

My understanding of array operations is that it would be incorrect to use the first array_load in the second part of the where statement lowering given it was created when the temp was not initialized with the mask value.

Comment (jeanPerier) [reply flang/test/Lower/where.f90]: Updated to use fir.array_coor.

**Review by schweitzpgi — APPROVED** [review]
I'm actively working on this, so need to merge it.
