### PR TITLE
Simplify type lowering and reflect constant length in more cases

### LINKED ISSUE #539: [FCVS regression] assumed length character parameter lowering fails f715
`error: loc("fm715.f":40:21): 'fir.convert' op invalid type conversion`
Caused by a `fir.array<6xfir.char<kind>>` being casted to `fir.array<?xfir.char<kind>>`.
reproducer:
```
 character(*), parameter :: c = "hello"
 print *, c
end
```

### PR DESCRIPTION
**Pull request by jeanPerier**
- Refactor type conversions.
    - remove unused/untested entry points
    - replace `TypeBuilder` by a version that do not visit expressions (use front-end tools to get shape/dynamic type instead)
- Get length of assumed length named constant in mlir type (we cannot get it directly from the symbol). This fixes #539 
- Use `expr.LEN()` for expression instead of dynamic type length info that does not always hold an explicit length in cases where it can be deduced from the expression but is not a length coming from a declaration (like `a // b` where `a` and `b` have compiled time constant length).

### CODE REVIEW

File: flang/lib/Lower/ConvertType.cpp [hunk 1]
```diff
@@ -18,384 +18,184 @@
...
-  // breaks the conflict between A<Type<TC,KIND>> and Expr<B> deduction
-  template <Fortran::common::TypeCategory TC, int KIND>
-  mlir::Type
-  gen(const Fortran::evaluate::Expr<Fortran::evaluate::Type<TC, KIND>> &) {
-    return genFIRType<TC, KIND>(context);
-  }
+  mlir::Type genExprType(const Fortran::lower::SomeExpr &expr) {
+    auto dynamicType = expr.GetType();
+    if (!dynamicType)
+      llvm::report_fatal_error("lowering typeless expression type");
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertType.cpp:125]: How is the client supposed to deal with these? Should this be an `llvm::Optional` type return?

File: flang/lib/Lower/ConvertType.cpp [hunk 2]
```diff
@@ -411,185 +211,86 @@ class TypeBuilder {
...
+  // the symbol to cover the case where the symbol is an assumed length named
+  // constant and its length comes from its init expression length.
+  template <int Kind>
+  fir::SequenceType::Extent
+  getCharacterLengthHelper(const Fortran::semantics::Symbol &symbol) {
+    using TC =
+        Fortran::evaluate::Type<Fortran::common::TypeCategory::Character, Kind>;
+    auto designator = Fortran::evaluate::Fold(
+        foldingContext,
+        Fortran::evaluate::Expr<TC>{Fortran::evaluate::Designator<TC>{symbol}});
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertType.cpp:224]: Why doesn't the front-end already fold these? It seems like it really should.

File: flang/lib/Lower/ConvertType.cpp [hunk 3]
```diff
@@ -411,185 +211,86 @@ class TypeBuilder {
...
+    case 4:
+      return getCharacterLengthHelper<4>(symbol);
     }
-    // LOGICAL, INTEGER, REAL, COMPLEX
-    fir::SequenceType::Shape shape{};
-    translateShape(shape, std::move(*shapeExpr));
-    if (!shape.empty())
-      return fir::SequenceType::get(shape, baseType);
-    return baseType;
+    llvm::report_fatal_error("unknown character kind");
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertType.cpp:246]: I think we could even use the weaker `llvm_unreachable` here, as the KIND values are hard-coded into the front-end.

File: flang/lib/Lower/ConvertType.cpp [hunk 4]
```diff
@@ -411,185 +211,86 @@ class TypeBuilder {
...
-      auto extent = fir::SequenceType::getUnknownExtent();
-      if (auto constantExtent = toInt64(std::move(extentExpr)))
-        extent = *constantExtent;
-      shape.push_back(extent);
-    }
+  fir::SequenceType::Extent
+  getCharacterLength(const Fortran::lower::SomeExpr &expr) {
+    // Do not use dynamic type length here. We would miss constant
+    // lengths opportunities because dynamic type only has the length
+    // if it comes from a declaration.
```
Comment (schweitzpgi) [inline flang/lib/Lower/ConvertType.cpp:252]: Not sure why there is this and the helper function. Again, it seems like the LEN would already be folded by the front-end like other `Ev::Expr`s.

**Review by schweitzpgi — COMMENTED** [review]
I'm wondering if we can't lean on the front-end even more and assume it is going to fold the expressions already. Then we could skip threading around the FoldingContext through the bridge.

File: flang/lib/Lower/ConvertType.cpp (hunk 1 above)
Comment (jeanPerier) [reply flang/lib/Lower/ConvertType.cpp:125]: Good point. The previous code would return `genTypelessPtr` (pointer to empty tuple) for all typless expression, but this was not used.
Typeless expressions are:
- BOZLiteralConstant -> let's use `NoneType` (I think these do not hit lowering since they are folded to whatever type they should be according to the context they appear in.)
- NullPointer -> let's use  `fir.ref<NoneType>` since that's what is used by [createNullConstant](https://github.com/flang-compiler/f18-llvm-project/blob/f75fcb9a706ba7b6cc22948ffbaf555c696c599b/flang/lib/Lower/FIRBuilder.cpp#L49).
- ProcedureDesignator -> That one is not typeless in FIR since we have function types. So we should return it.
- ProcedureRef -> subroutine calls return value, I guess `NoneType` could also be used here.

Again, right now there are no clients for those, so maybe a hard TODO is better until there is a use case and we can pick the type according to the use case need.

File: flang/lib/Lower/ConvertType.cpp (hunk 2 above)
Comment (jeanPerier) [reply flang/lib/Lower/ConvertType.cpp:224]: Here, we are building an expression that is unrelated to the expressions from the parse tree. The front-end does not fold expression when you build them, so we need to fold. The folding of designator allow to resolve the link between a named constant parameter and its init expression.
I feel like that we should not have to fold a Designator and that LEN() of a designator should deal with this case. I will propose this to Peter and remove this Fold once this is done in the front-end and we can remove this fold.
Otherwise, we could also handle the implied length case manually here.

File: flang/lib/Lower/ConvertType.cpp [hunk 5]
```diff
@@ -18,384 +18,184 @@
...
+    return genCharacterType(context, kind);
+  default:
+    break;
+  }
+  llvm_unreachable("unhandled type category");
+}
 
-  template <template <typename> typename A, Fortran::common::TypeCategory TC>
-  mlir::Type gen(const A<Fortran::evaluate::SomeKind<TC>> &) {
-    return genFIRType<TC>(context, defaultKind<TC>());
```
[the remark this answers is not in the document]
Comment (jeanPerier) [reply flang/lib/Lower/ConvertType.cpp:185]: Not that I know of. Also, the `SomeKind` name may be misleading here, `A<SomeKind<TC>>` usually contains a  member u `std::variant<A<Type<TC, KIND1>>, A<Type<TC, KIND2>>, ....>`. Anyway, I am not aware of front-end expr that comes out without the KIND being resolved today.

File: flang/lib/Lower/ConvertType.cpp (hunk 4 above)
Comment (jeanPerier) [reply flang/lib/Lower/ConvertType.cpp:252]: Regarding the folding in `toInt64`, it's needed because for the shape and length because we are getting `ev::Expr` created by the front-end when we call `LEN()`/`GetShape`.
Evaluate does not fold the expressions its tool generates, it leaves it up to the client to call Fold if desired.
`ev::Expr` that are under parse-tree node have been folded by semantics analysis (client of Evaluate), but the one we are dealing with here are expr we just generated here.

The comment here is however not related to folding, it's related to the fact that the length in the DynamicType cannot represent all character expressions lengths ([see comment here.](https://github.com/flang-compiler/f18-llvm-project/blob/c757418869c01f5ee08f05661debabbba92edcf9/flang/include/flang/Evaluate/type.h#L78-L85)). This is a very non trivial design choice from the front-end, that I think deserve outlining this in a helper so we can justify not using the length DynamicType we have above and that really looks like we should be using when we should not.

Note that this is not the case for derived type lengths parameters, since they are always linked to a derived type declarartion and can therefore always be represented in DynamicTypes.

**Comment by jeanPerier** [comment]
> I'm wondering if we can't lean on the front-end even more and assume it is going to fold the expressions already. Then we could skip threading around the FoldingContext through the bridge.

I see you point, but I don't think it is possible without redoing all the shape and length analysis ourselves (basically re-implementing a subset of folding by hand here to get the lengths/shapes).

The expressions we fold here are not "user expressions", they are expressions generated by evaluate tools (Shape and Length analysis). Evaluate tools leaves it up to the client decide to fold them or not. So if we do not Fold these here, we would end-up with `?` lengths and extents in places we should not.

Also, even if evaluate tools that generate "compiler generated" `ev::Expr` would fold that directly for us, that would imply that we would need to provide these tools (expr.LEN() and Shape analysis) with a folding context when we use them here, so we would still need to thread it.

File: flang/lib/Lower/ConvertType.cpp (hunk 1 above)
Comment (jeanPerier) [reply flang/lib/Lower/ConvertType.cpp]: I added handling for typeless expr in the latest commit. That required threading the `AbstractConverter`  so that we can use the call interface signature lowering on the `ProcedureDesignator`. But I took the opportunity of having this at hand to remove the foldingContext/mlirContext threading and lower symbol location for better mlir::emitError messages.

File: flang/lib/Lower/ConvertType.cpp (hunk 4 above)
Comment (schweitzpgi) [reply flang/lib/Lower/ConvertType.cpp:286]: It's not very clear when an `Ev::Expr` is folded in the front-end vs. when it isn't. Sometimes an entire array of floats is folded elementally, but apparently `GetShape` (where we want constants over symbolic names) does not.

Comment (schweitzpgi) [reply flang/lib/Lower/ConvertType.cpp:286]: As to this comment, should we have some sort of helper that can determine the "other" constant cases that are being dropped on the floor?

**Comment by schweitzpgi** [comment]
> > I'm wondering if we can't lean on the front-end even more and assume it is going to fold the expressions already. Then we could skip threading around the FoldingContext through the bridge.
> 
> I see you point, but I don't think it is possible without redoing all the shape and length analysis ourselves (basically re-implementing a subset of folding by hand here to get the lengths/shapes).
> 
> The expressions we fold here are not "user expressions", they are expressions generated by evaluate tools (Shape and Length analysis). Evaluate tools leaves it up to the client decide to fold them or not. So if we do not Fold these here, we would end-up with `?` lengths and extents in places we should not.
> 
> Also, even if evaluate tools that generate "compiler generated" `ev::Expr` would fold that directly for us, that would imply that we would need to provide these tools (expr.LEN() and Shape analysis) with a folding context when we use them here, so we would still need to thread it.

It sounds like we're going to end up with `?` extents in some places (CHARACTER) regardless. Have you looked at MLIR's shape analysis any? MLIR has it's own constant folding (as does LLVM), so there's an argument there as well.

**Comment by jeanPerier** [comment]
> It sounds like we're going to end up with `?` extents in some places (CHARACTER) regardless. Have you looked at MLIR's shape analysis any? MLIR has it's own constant folding (as does LLVM), so there's an argument there as well.

I did not look at MLIR folding yet. In general, I do not expect it yet to fold all the Fortran expressions that are constant expressions (e.g, we have way more intrinsic, and I am not sure how efficient MLIR would be at folding lowered TRIM right now (it would need to run the loops), or those for which there is no cmath/llvm intrinsics and we use pgmaths).

Anyway, here if I remove the Fold call, we do generate incorrect FIR code that does not lower/crash at code gen. Mainly, we generate `fir.array<? x kind>` types in value context (i.e, no ref around).

We are not short-circuiting FIR/MLIR with the Folds on these expressions since we are not sticking those under the parse-tree and they will not be lowered to FIR (they are compiler generated expr for "internal analysis purpose"), we are just replacing the manual length/shape computation that were previously done ([for instance here](https://github.com/flang-compiler/f18-llvm-project/blob/db94d8c13e39d2f2340a4f4fa950b6ea0ab8b213/flang/lib/Lower/ConvertType.cpp#L442-L463)) in this file to represent that in FIR type system.

In general, I understand your reluctance using `evaluate::Fold` given its massive use in the front-end is debatable (e.g unconditionally folding huge arrays even if we do not need the value at compile time), but here we are really only trying to fold bounds and lengths expr and the front-end has a really good Fortran expression shape/length analysis, and I think it would be a pity dropping this on the floor just to avoid the Fold here.

**Review by schweitzpgi — APPROVED** [review]
