### PR TITLE
Fix #857 - assignment to contiguous local pointer from a fir.box

### LINKED ISSUE #857: bbc: void (anonymous namespace)::(anonymous namespace)::MutablePropertyWriter::updateWithIrBox(mlir::Value): Assertion `!box.isDescribedByVariables()' failed.
`bbc` crashed on the following piece of code.

```fortran
      module mod_hash

      implicit none

      type capsule
      integer :: jndx,val_pos
      type(capsule), pointer :: pntr
      end type capsule

      type(capsule), dimension(:), target, allocatable :: hash

      contains


      subroutine print_hash()
      implicit none
      integer :: i
      type(capsule), pointer :: dummy

      do i=lbound(hash,1),ubound(hash,1)
      dummy => hash(i)
      do while(associated(dummy%pntr))
         dummy => dummy%pntr
      end do
      end do
      end subroutine print_hash

      end module mod_hash
```

Here's the stack dump

```
Stack dump:
0.      Program arguments: /home/ryuta/packages/llvm/flang/build/bin/bbc ./hash.f90
 #0 0x00007ff2eb7afc73 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x229c73)
 #1 0x00007ff2eb7ad57e llvm::sys::RunSignalHandlers() (/hom/ryuta/packages/llvm/flang/build/lib/libLLVMSupport.so.13git+0x22757e)
 #2 0x00007ff2eb7b02ef SignalHandler(int) Signals.cpp:0:0
 #3 0x00007ff2ef8fc630 __restore_rt sigaction.c:0:0
 #4 0x00007ff2eadb9387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007ff2eadbaa78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007ff2eadb21a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007ff2eadb2252 (/lib64/libc.so.6+0x2f252)
```

### PR DESCRIPTION
**Pull request by jeanPerier**
Fix #857.
Scalar and contiguous pointer assignment may be lowered to a set of local variable instead of a fir.re<fir.box>, in which case they should not be updated with a fir.box. It is possible that the RHS of assignments to such pointers is lowered to a fir.box because the contiguous aspects of the RHS may not be obvious or guaranteed in lowering.

Add handling for this case by reading the fir.box to implement the pointer assignment.

On the way, fix two related issues:
 - missing casts before store when updating the local variables
   representing the pointer. There were i64 to index store issues
   otherwise in some cases.
 - Alloca/Allocmem did not allow to allocate a fir.ptr<fir.array<?x...xT>>
   which is needed to track the address of a contiguous local array
   pointer. The alloc verify was going through the fir.ptr and then
   complained that not extents was provided in the alloc for the
   fir.array type. This looks bogus to me, and I do not see the
   purpose of this check, so I removed it.

### CODE REVIEW

**Review by vdonaldson — APPROVED** [review]

File: flang/lib/Lower/Allocatable.cpp [hunk 1]
```diff
@@ -1196,20 +1215,36 @@ void Fortran::lower::associateMutableBoxWithRemap(
...
+            lenParams.emplace_back(
+                Fortran::lower::readCharLen(builder, loc, source));
+          } else if (arr.isDerivedWithLengthParameters()) {
+            TODO(loc, "pointer assignment to derived with length parameters");
+          }
+          writer.updateMutableBox(rawAddr, lbounds, extents, lenParams);
+        } else {
+          auto shapeType =
+              fir::ShapeShiftType::get(builder.getContext(), extents.size());
+          SmallVector<mlir::Value> shapeArgs;
```
Comment (schweitzpgi) [inline flang/lib/Lower/Allocatable.cpp:1234]: llvm::SmallVector ?

**Review by schweitzpgi — APPROVED** [review]
